set(_CATKIN_CURRENT_PACKAGE "wam_description")
set(wam_description_MAINTAINER "Steve Levine <steve@todo.todo>")
set(wam_description_DEPRECATED "")
set(wam_description_VERSION "1.0.0")
set(wam_description_BUILD_DEPENDS "xacro")
set(wam_description_RUN_DEPENDS "xacro")
set(wam_description_BUILDTOOL_DEPENDS "catkin")